### ISSUE TITLE
Doesn't do anything if text is ALL CAPS

### ISSUE THREAD

**Issue by GlitterHorn** [AWtnb/vscode-smart-title-case#3]
Repro:

  1. Enter string in ALL CAPS
  2. Select string
  3. Use smart-title-case to convert text
  4. Nothing happens
  5. Use built-in "transform to lowercase"
  6. Use smart-title-case to convert text
  7. Text transforms properly

**Comment by AWtnb** [comment]
Thanks for issue! But it is by design.

I created this extension to manually format the bibliography of an article.

Many abbreviations such as `DNA` or `NPO` appear in academic journals. Converting them to, for example, `Dna` or `Npo` would result in improper spelling, so this extension does not convert any all-caps words.

**Comment by AWtnb** [comment]
It has been a while.
In version 0.5.0, new `-strictly` commands convert all-caps words strictly as well.
I hope this helps.

**Comment by GlitterHorn** [comment]
Thank you very much for adding this feature. I've already made liberal use of it! 👌
